---
name: ✨ Feature request
description: Suggest an idea for this project
body:
  - type: markdown
    attributes:
      value: |
        Feature Request issues are for **feature requests** only.
        For debugging help or technical support, please see the [Get Involved section of our README](https://github.com/ansible/awx#get-involved)

  - type: checkboxes
    id: terms
    attributes:
      label: Please confirm the following
      options:
        - label: I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
          required: true
        - label: I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
          required: true
        - label: I understand that AWX is open source software provided for free and that I might not receive a timely response.
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: Briefly describe the desired enhancement.
    validations:
      required: true

  - type: checkboxes
    id: components
    attributes:
      label: Select the relevant components
      options:
        - label: UI
        - label: API
        - label: Docs
        - label: Collection
        - label: CLI
        - label: Other

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: >-
        Starting from a new installation of the system, describe exactly how a developer or quality engineer can reproduce the scenario
        on infrastructure that isn't yours. Include any and all resources created, input values, test users, roles assigned, playbooks used, etc.
    validations:
      required: true

  - type: textarea
    id: current-results
    attributes:
      label: Current results
      description: What happens when running the steps above?
    validations:
      required: true

  - type: textarea
    id: sugested-results
    attributes:
      label: Sugested feature result
      description: What could happen to improve the system or user experience?
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Include any relevant log output, links to sosreport, database dumps, screenshots, or other information.
    validations:
      required: false